TweakPropertyGenerator Phase 6
agroGandhi/JustTweak pull request #6
Opened 2021-04-19 16:44 UTC by albertodebortoli

- Rename 'configuration' to 'tweakProvider' all over the place.
- A lot more collateral renaming.

2021-04-20 13:43 UTC, agroGandhi requested changes

2021-04-20 13:43 UTC, agroGandhi commented on Example/Tests/Core/LocalTweakProviderTests.swift
> +        tweakProvider = tweakProviderWithFileNamed("test_tweaks")!
should we try and do a similar name to the configuration file such as:
`LocalTweaks_test`

2021-04-20 13:43 UTC, agroGandhi commented on README.md
>  - post a `TweakConfigurationDidChangeNotification` notification
Should we change the `TweakConfigurationDidChangeNotification`?

2021-04-20 13:43 UTC, agroGandhi commented on TweakAccessorGenerator/TweakAccessorGenerator/main.swift
>      @Option(name: .shortAndLong, help: "The local configuration file path.")
maybe we should still include local here as we name the providers "LocalTweakProvider":
`localTweaksFilePath `

Also we need to update the help string

2021-04-20 13:43 UTC, agroGandhi commented on TweakAccessorGenerator/TweakAccessorGeneratorTests/Suites/TweakLoaderTests.swift
> +        let tweaksFilename = "Tweaks"
do we need `test_tweaks` and `test_tweaks_override` in the other tests? Filenames are lowercased but feels like we have a fair few files now

2021-04-20 15:57 UTC, albertodebortoli commented on README.md
>  - post a `TweakConfigurationDidChangeNotification` notification
Very well spotted! I had it on my list but forgot to tackle it!

2021-04-20 17:46 UTC, albertodebortoli commented on Example/Tests/Core/LocalTweakProviderTests.swift
> +        tweakProvider = tweakProviderWithFileNamed("test_tweaks")!
Yep!

2021-04-20 17:52 UTC, albertodebortoli commented on TweakAccessorGenerator/TweakAccessorGeneratorTests/Suites/TweakLoaderTests.swift
> +        let tweaksFilename = "Tweaks"
I've renamed them to `LocalTweaks_test.json` and `LocalTweaks_test_override.json`, still used in `TweakManager+PresentationTests.swift`, `LocalTweakProviderTests.swift`, `TweakManagerTests.swift` and `TweakViewControllerTests.swift`.
What we don't need anymore are these 2 files: `test_tweaks_invalid.json` and `test_tweaks_no_displayable_ungrouped.json`

2021-04-21 08:30 UTC, agroGandhi approved these changes

2021-04-21 09:27 UTC, merged